version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: kafka1
      KAFKA_OPTS: "-javaagent:/opt/kafka_2.0.0/libs/jmx_prometheus_javaagent.jar=9101:/opt/kafka_2.0.0/config/kafka-2_0_0.yml"
    volumes:
      - ./kafka-2_0_0.yml:/opt/kafka_2.0.0/config/kafka-2_0_0.yml
      - ./jmx_prometheus_javaagent-0.16.0.jar:/opt/kafka_2.0.0/libs/jmx_prometheus_javaagent.jar
  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9093,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_JMX_PORT: 9102
      KAFKA_JMX_HOSTNAME: kafka2
      KAFKA_OPTS: "-javaagent:/opt/kafka_2.0.0/libs/jmx_prometheus_javaagent.jar=9102:/opt/kafka_2.0.0/config/kafka-2_0_0.yml"
    volumes:
      - ./kafka-2_0_0.yml:/opt/kafka_2.0.0/config/kafka-2_0_0.yml
      - ./jmx_prometheus_javaagent-0.16.0.jar:/opt/kafka_2.0.0/libs/jmx_prometheus_javaagent.jar
  kafka3:
    image: wurstmeister/kafka
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9093,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
      KAFKA_JMX_PORT: 9103
      KAFKA_JMX_HOSTNAME: kafka3
      KAFKA_OPTS: "-javaagent:/opt/kafka_2.0.0/libs/jmx_prometheus_javaagent.jar=9103:/opt/kafka_2.0.0/config/kafka-2_0_0.yml"
    volumes:
      - ./kafka-2_0_0.yml:/opt/kafka_2.0.0/config/kafka-2_0_0.yml
      - ./jmx_prometheus_javaagent-0.16.0.jar:/opt/kafka_2.0.0/libs/jmx_prometheus_javaagent.jar
  prometheus:
   image: prom/prometheus:v2.30.3
   ports:
     - "9090:9090"
   volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
   command:
     - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
   image: grafana/grafana:latest
   ports:
     - "3000:3000"

